omod/src/main/webapp/fragments/patientflagsDashboard.gsp

https://issues.openmrs.org/browse/FLAG-23

FLAG-23: Display the evaluated message for the patient which will include any place holders

---

api/src/main/java/org/openmrs/module/patientflags/api/FlagService.java
api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java
api/src/main/java/org/openmrs/module/patientflags/db/FlagDAO.java
api/src/main/java/org/openmrs/module/patientflags/db/hibernate/HibernateFlagDAO.java
omod/pom.xml
omod/src/main/java/org/openmrs/module/patientflags/util/WebUtils.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/FlagResource.java

https://issues.openmrs.org/browse/FLAG-34

WIP: FLAG-34 Subtask Flag Resource added

---

omod/src/main/java/org/openmrs/module/patientflags/web/rest/PatientFlagDisplayPointResource.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/PatientFlagTagResource.java

https://issues.openmrs.org/browse/FLAG-35

FLAG-35 - subtask added diplaypoint and tag resources

---

omod/src/main/java/org/openmrs/module/patientflags/web/rest/PatientFlagPriorityResource.java

https://issues.openmrs.org/browse/FLAG-36

FLAG-36 - REST service for PRIORITY

---

.travis.yml
omod/src/main/java/org/openmrs/module/patientflags/fragment/controller/PatientflagsDashboardFragmentController.java
omod/src/main/webapp/fragments/patientflagsDashboard.gsp

https://issues.openmrs.org/browse/FLAG-49

FLAG-49 Improve loading speed of Patient Dashboard

---

api/src/main/java/org/openmrs/module/patientflags/PatientFlagsModuleActivator.java

Enable patient flags to run in 2.2.0 platform
https://issues.openmrs.org/browse/FLAG-59

FLAG-59 : Enable patient flags to run in 2.2.0 platform

---

api/src/main/resources/DisplayPoint.hbm.xml
api/src/main/resources/Flag.hbm.xml
api/src/main/resources/Priority.hbm.xml
api/src/main/resources/Tag.hbm.xml
api/src/main/resources/liquibase.xml

**Changes I made**
1. Mapped sequence correctly.
2. Had to change name of index "role" since in the schema there already is a relation "role". This causes issue on PostgreSQL and index is not able to get created. 
**Link to ticket**
https://issues.openmrs.org/browse/FLAG-60

FLAG-60 Make Patient Flag module support PostgreSQL

---

pom.xml

changed java version 1.6 to 1.8
Issue work on : [FLAG-71](https://openmrs.atlassian.net/jira/software/c/projects/FLAG/list?selectedIssue=FLAG-71)
[FLAG-71]: https://openmrs.atlassian.net/browse/FLAG-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FLAG-71: Upgrade to java 8

---

.github/workflows/maven.yml

changed the workflow to build with different java versions
issue worked on [FLAG-74](https://openmrs.atlassian.net/browse/FLAG-74)
[FLAG-74]: https://openmrs.atlassian.net/browse/FLAG-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FLAG-74: Update the workflow to build with different java versions

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java

FLAG-75: refactor getFlaggedPatients method with stream API and lambda expressions

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java

FLAG-75: refactor purgePriority method with stream API

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java

FLAG-75: refactor getPatientFlags method with stream API

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java

FLAG-75: refactor getFlags method using stream API and lambda expressions 

---

pom.xml

Issue worked on : [FLAG-74](https://openmrs.atlassian.net/browse/FLAG-74)
[FLAG-74]: https://openmrs.atlassian.net/browse/FLAG-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FLAG-74: added java 17 profile

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java
api/src/main/java/org/openmrs/module/patientflags/task/PatientFlagTask.java

Reverting this because of the build error.

Revert "FLAG-69:  Improve the performance of the evaluating all flags"

---

api/src/main/java/org/openmrs/module/patientflags/task/PatientFlagTask.java

refactor the evaluate all flag opeate in parallel 
Evaluate all flags 10 times
parallel process -> 53, 58 , 73 . 51 , 46, 57 , 58, 63 , 52 => avg 51.1 milliseconds
current module -> 258, 230, 215, 208, 207, 208, 204, 196,202, 198 => avg 212.6 milliseconds
see https://openmrs.atlassian.net/browse/FLAG-69
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure …

FLAG-69: Improve the performance of the evaluating all flags

---

api/src/test/java/org/openmrs/module/patientflags/FlagServiceTest.java
api/src/test/resources/org/openmrs/module/patientflags/include/flagtest-dataset.xml
api/src/test/resources/org/openmrs/module/patientflags/include/patientflagtest-dataset.xml

added unit tests for flag service class

FLAG 78 : Add unit test for patient flags

---

omod/src/main/webapp/fragments/patientflagsDashboard.gsp

fixed the patient flags rendering issue on platform lower versions
see https://openmrs.atlassian.net/browse/FLAG-67

FLAG-67: Fix rendering of flags via simple objects that is currently broken in platform version greater than 2.5.* 

---

api/src/test/java/org/openmrs/module/patientflags/FlagServiceTest.java
api/src/test/resources/org/openmrs/module/patientflags/include/patientflagtest-dataset.xml

added missing unit tests for priority services

FLAG-78: Added test for priority services

---

api/src/test/java/org/openmrs/module/patientflags/FlagServiceTest.java
api/src/test/resources/org/openmrs/module/patientflags/include/patientflagtest-dataset.xml
api/src/test/resources/test-hibernate.cfg.xml

Added unit test for patient flags services

FLAG 78: Added unit tests for patient flag

---

pom.xml

Upgrade the openmrs version  2.0 to 2.2 in main pom.xml file
see https://openmrs.atlassian.net/browse/FLAG-73

FLAG-73: Upgrade openMRS version 2.0 to 2.2

---

api/src/main/java/org/openmrs/module/patientflags/db/hibernate/HibernateFlagDAO.java

FLAG-75: refactor dao method with stream API

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java

FLAG-75: refactor getFilter method with stream API

---

api/src/test/java/org/openmrs/module/patientflags/filter/FilterTest.java

Added unit test for flag filters

FLAG-78: Added test for flag filter class

---

omod/src/main/java/org/openmrs/module/patientflags/web/FindFlaggedPatientsController.java

Fixed the error in get flagged patients based on tags
[Screencast from 07-12-2024 10:15:35 PM.webm](https://github.com/user-attachments/assets/157b7443-9397-4851-915f-56814e4ec703)
see https://openmrs.atlassian.net/browse/FLAG-70
No? Unsure? -> execute command `git pull --rebase upstream …

FLAG-70: Get flagged patient based on tags is not working

---

api/src/main/java/org/openmrs/module/patientflags/api/impl/FlagServiceImpl.java
api/src/main/java/org/openmrs/module/patientflags/db/FlagDAO.java
api/src/main/java/org/openmrs/module/patientflags/db/hibernate/HibernateFlagDAO.java
api/src/main/java/org/openmrs/module/patientflags/task/PatientFlagTask.java

when evaluating the all flags, delete the all patient flags instead delete it one by one
see https://openmrs.atlassian.net/browse/FLAG-80

FLAG-80: fixed the exception in evaluate all flags

---

.github/workflows/maven.yml
api-metadata/pom.xml
api/pom.xml
api/src/main/java/org/openmrs/module/patientflags/evaluator/CQLFlagEvaluator.java
omod/pom.xml
pom.xml

see https://openmrs.atlassian.net/browse/FLAG-

Fix CQLFlagEvaluator

---

api/src/test/java/org/openmrs/module/patientflags/PatientFlagTaskTest.java

Added unit test for patientFlagTask class

FLAG-78: Added tests class for PatientTask class

---

omod/src/main/java/org/openmrs/module/patientflags/web/rest/resources/PatientFlagDisplayPointResource.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/resources/PatientFlagFlagResource.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/resources/PatientFlagPriorityResource.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/resources/PatientFlagResource.java
omod/src/main/java/org/openmrs/module/patientflags/web/rest/resources/PatientFlagTagResource.java
pom.xml

see https://openmrs.atlassian.net/browse/RESTWS-957

RESTWS-957: Fix Swagger errors displayed on the openmrs swagger api docs page
